sylva-etl:
  enabled: false
  archive-enabled: false
database:
  host: localhost
  port: 27017
  user: sylva
  password: changeit
folders:
  incoming: /home/sylva/incoming
  storage: /home/sylva/storage
  trash: /home/sylva/trash
hooks:
  BAA500: 
  - "date"