#!/bin/bash

# simple store with positive result
cd /home/sylva
cp testdata/baa500.zip incoming/
cp testdata/poleno.zip incoming/

cat /etc/sylva-etl/sylva-config.yaml | sed -i "s/enabled: false/enabled: true/" /etc/sylva-etl/sylva-config.yaml && \

sylva-store

if [ ! -f "/home/sylva/storage/Schneefernerhaus/Poleno/2023/09/18/poleno.zip" ]; then
    echo "File poleno.zip not at expected place."
    exit 1
fi

if [ ! -f "/home/sylva/storage/Schneefernerhaus/BAA500/2020/02/22/baa500.zip" ]; then
    echo "File baa500.zip not at expected place."
    exit 1
fi

if [ ! -z "$(ls -A /home/sylva/incoming)" ]; then
    echo "Incoming folder is not empty but was expected to be empty."
    exit 1
fi

# same file with different hash code should lead to trash 
cp testdata/baa500.otherhash incoming/baa500.zip

sylva-store

if [ ! -n "$(find "/home/sylva/trash" -type f -name "*-baa500.zip")" ]; then 
    echo "File expected in trash is not there."
    exit 1
fi


# duplicate file
cp testdata/poleno.zip incoming/poleno-duplicate.zip
sylva-store

if [ ! -n "$(find "/home/sylva/trash" -type f -name "*-poleno-duplicate.zip")" ]; then 
    echo "File expected in trash is not there."
    exit 1
fi

# trash file
cp testdata/invalid.zip incoming/
sylva-store

if [ ! -n "$(find "/home/sylva/trash" -type f -name "*-invalid.zip")" ]; then 
    echo "File expected in trash is not there."
    exit 1
fi

cat /etc/sylva-etl/sylva-config.yaml | sed -i "s/enabled: true/enabled: false/" /etc/sylva-etl/sylva-config.yaml