#!/bin/bash

# simple store with positive result
cd /home/sylva

mkdir foo_incoming
mkdir foo_storage
mkdir foo_trash

cp testdata/baa500.zip foo_incoming
cp testdata/poleno.zip foo_incoming

sylva-store --incomingDir /home/sylva/foo_incoming --storageDir /home/sylva/foo_storage --trashDir /home/sylva/foo_trash --overrideEnabled

if [ ! -f "/home/sylva/foo_storage/Schneefernerhaus/Poleno/2023/09/18/poleno.zip" ]; then
    echo "File poleno.zip not at expected place."
    exit 1
fi

if [ ! -f "/home/sylva/foo_storage/Schneefernerhaus/BAA500/2020/02/22/baa500.zip" ]; then
    echo "File baa500.zip not at expected place."
    exit 1
fi

if [ ! -z "$(ls -A /home/sylva/foo_incoming)" ]; then
    echo "Incoming folder is not empty but was expected to be empty."
    exit 1
fi

# duplicate file
cp testdata/poleno.zip foo_incoming/poleno-duplicate.zip
sylva-store --incomingDir /home/sylva/foo_incoming --storageDir /home/sylva/foo_storage --trashDir /home/sylva/foo_trash --overrideEnabled

if [ ! -n "$(find "/home/sylva/foo_trash" -type f -name "*-poleno-duplicate.zip")" ]; then 
    echo "File expected in trash is not there."
    exit 1
fi

# trash file
cp testdata/invalid.zip foo_incoming/
sylva-store --incomingDir /home/sylva/foo_incoming --storageDir /home/sylva/foo_storage --trashDir /home/sylva/foo_trash --overrideEnabled

if [ ! -n "$(find "/home/sylva/foo_trash" -type f -name "*-invalid.zip")" ]; then 
    echo "File expected in trash is not there."
    exit 1
fi
