#!/bin/bash

path=$(uuidgen)
mkdir $path
mkdir $path/incoming
mkdir $path/archive
mkdir $path/trash

cp ../test/testdata/*.zip $path/incoming/

sylva-archive --incomingDir $path/incoming --archiveDir $path/archive --trashDir $path/trash

rm $path -r