#!/bin/bash

path=$(uuidgen)
mkdir $path
mkdir $path/incoming
mkdir $path/storage
mkdir $path/trash

cp ../test/testdata/*.zip $path/incoming/

sylva-store --incomingDir $path/incoming --storageDir $path/storage --trashDir $path/trash

rm $path -r