name: Test Debian Package

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Test Docker Image
        run: |
          cd test
          docker build .
